-- Biblioteca EE 11 de Outubro
-- Importa somente metadados da planilha original nos 398 títulos existentes.
-- Não cria títulos, não altera quantidades e não apaga exemplares.

begin;

alter table public.livros
  add column if not exists ordem_planilha integer,
  add column if not exists genero_codigo text,
  add column if not exists classificacao_numero text,
  add column if not exists classificacao_cor text,
  add column if not exists classificacao_cor_hex text;

alter table public.exemplares
  add column if not exists tombamento text;

create or replace function pg_temp.normalizar_catalogo(valor text)
returns text
language sql
immutable
as $$
  select btrim(
    regexp_replace(
      translate(
        lower(coalesce(valor, '')),
        'áàãâäéèêëíìîïóòõôöúùûüçñ',
        'aaaaaeeeeiiiiooooouuuucn'
      ),
      '\s+',
      ' ',
      'g'
    )
  );
$$;

create temporary table catalogo_planilha_original (
  titulo_chave text primary key,
  titulo_original text not null,
  autor_original text,
  categoria text not null,
  ordem_planilha integer,
  genero_codigo text,
  classificacao_numero text,
  classificacao_cor text,
  classificacao_cor_hex text
) on commit preserve rows;

insert into catalogo_planilha_original (
  titulo_chave,
  titulo_original,
  autor_original,
  categoria,
  ordem_planilha,
  genero_codigo,
  classificacao_numero,
  classificacao_cor,
  classificacao_cor_hex
) values
('6 vezes lucas','6 Vezes Lucas','Lygia Bojunga','Literatura brasileira contemporânea',1,'LBC',null,null,null),
('a angustia das pequenas coisas ridiculas','A angústia das pequenas coisas ridículas','Luisa Geisler','Literatura brasileira contemporânea',2,'LBC',null,null,null),
('a colina dos suspiros','A Colina dos Suspiros','Moacyr Scliar','Literatura brasileira contemporânea',3,'LBC',null,null,null),
('a estacao das pequenas coisas','A Estação das Pequenas Coisas','João Anzanello Carrascozza','Literatura brasileira contemporânea',4,'LBC',null,null,null),
('a familia dionti','A Família Dionti','Alan Minas','Literatura brasileira contemporânea',5,'LBC',null,null,null),
('a filha do escritor','A Filha do Escritor','Gustavo Bernardo','Literatura brasileira contemporânea',6,'LBC',null,null,null),
('a lua vem da asia','A Lua vem da Ásia','Campos de Carvalho','Literatura brasileira contemporânea',7,'LBC',null,null,null),
('a majestade do xingu','A Majestade do Xingu','Moacyr Scliar','Literatura brasileira contemporânea',8,'LBC',null,null,null),
('a maldicao das fadas','A Maldição das Fadas','Marcos Mota','Literatura brasileira contemporânea',9,'LBC',null,null,null),
('a muralha','A muralha','Dinah Silveira de Queiroz','Literatura brasileira contemporânea',10,'LBC',null,null,null),
('a pequena prisao','A Pequena Prisão','Igor Mendes','Literatura brasileira contemporânea',11,'LBC',null,null,null),
('a roda da vida','A Roda da vida','Manuel Filho','Literatura brasileira contemporânea',12,'LBC',null,null,null),
('alek ciaran e os guardioes da escuridao','Alek Ciaran e os guardiões da escuridão','Shirley Souza','Literatura brasileira contemporânea',13,'LBC',null,null,null),
('amara e beijo frio','Amara e Beijo Frio','Adriano Messias','Literatura brasileira contemporânea',14,'LBC',null,null,null),
('as amigas que fiz','As amigas que fiz','Andréa Pelagagi','Literatura brasileira contemporânea',15,'LBC',null,null,null),
('as santas','As Santas','Neir Ilelis','Literatura brasileira contemporânea',16,'LBC',null,null,null),
('as vidas e as mortes de frankestein','As vidas e as mortes de Frankestein','Jeanette Rozsas','Literatura brasileira contemporânea',17,'LBC',null,null,null),
('assassinato na biblioteca','Assassinato na Biblioteca','Helena Gomes','Literatura brasileira contemporânea',18,'LBC',null,'Verde','#16a34a'),
('avante soldados: para tras','Avante soldados: para trás','Deonísio da Silva','Literatura brasileira contemporânea',19,'LBC',null,null,null),
('becos da memoria','Becos da Memória','Conceição Evaristo','Literatura brasileira contemporânea',20,'LBC',null,null,null),
('bob kurt','Bob Kurt','Ricardo Estevão','Literatura brasileira contemporânea',21,'LBC',null,null,null),
('cabra-cega','Cabra-cega','Cacau Vilardo','Literatura brasileira contemporânea',22,'LBC',null,null,null),
('cafeina','Cafeína','Maurício Torres Assumpção','Literatura brasileira contemporânea',23,'LBC',null,null,null),
('caleidoscopio de vidas','Caleidoscópio de vidas','João Anzanello Carrascozza','Literatura brasileira contemporânea',24,'LBC',null,null,null),
('caminho para ver estrelas','Caminho para ver estrelas','Lúcia Teixeira','Literatura brasileira contemporânea',25,'LBC',null,null,null),
('canto do uirapuru','Canto do Uirapuru','Érica Bombardi','Literatura brasileira contemporânea',26,'LBC',null,null,null),
('casa dos braga - memoria de infancia','Casa dos Braga - Memória de Infância','Rubem Braga','Literatura brasileira contemporânea',27,'LBC',null,null,null),
('chama e cinzas','Chama e cinzas','Carolina Nabuco','Literatura brasileira contemporânea',28,'LBC',null,null,null),
('ciranda de pedra','Ciranda de Pedra','Lygia Fagundes Telles','Literatura brasileira contemporânea',29,'LBC',null,null,null),
('confraria van gogh - a vida secreta de um livro de biblioteca publica','Confraria Van Gogh - a vida secreta de um livro de biblioteca pública','Mirian da Silva Cavalcanti','Literatura brasileira contemporânea',30,'LBC',null,null,null),
('crescer e perigoso','Crescer é Perigoso','Marcia Kupstas','Literatura brasileira contemporânea',31,'LBC',null,null,null),
('de volta a caixa de desejos','De volta à Caixa de Desejos','Ana Cristina Melo','Literatura brasileira contemporânea',32,'LBC',null,null,null),
('delta - um comando para o tempo','Delta - Um Comando para o Tempo','Ana Cristina Melo','Literatura brasileira contemporânea',33,'LBC',null,null,null),
('depois a louca sou eu','Depois a louca sou eu','Tati Bernardi','Literatura brasileira contemporânea',34,'LBC',null,null,null),
('depois daquela viagem','Depois daquela viagem','Valéria Piassa Polizzi','Literatura brasileira contemporânea',35,'LBC',null,null,null),
('depois daquele domingo ou a historia de teresas e de joao','Depois daquele domingo ou A História de Teresas e de João','Caio Riter','Literatura brasileira contemporânea',36,'LBC',null,null,null),
('dinamene','Dinamene','Maicon Tenfen','Literatura brasileira contemporânea',37,'LBC',null,null,null),
('duny meu livro. eu que escrevi.','DUNY Meu Livro. Eu Que Escrevi.','Raony Phillips','Literatura brasileira contemporânea',38,'LBC',null,null,null),
('em busca do passado perdido','Em busca do passado perdido','Jessica Spilla','Literatura brasileira contemporânea',39,'LBC',null,null,null),
('essa terra','Essa Terra','Antônio Torres','Literatura brasileira contemporânea',40,'LBC',null,null,null),
('estacao carandiru','Estação Carandiru','Drauzio Varella','Literatura brasileira contemporânea',41,'LBC',null,null,null),
('fantina - cenas de escravidao','Fantina - Cenas de escravidão','F.C. Duarte Badaró','Literatura brasileira contemporânea',42,'LBC',null,null,null),
('feliz ano velho','Feliz Ano Velho','Marcelo Rubens Paiva','Literatura brasileira contemporânea',43,'LBC',null,null,null),
('ian nao esta mais aqui','Ian não está mais aqui','Luiz Antonio Aguiar','Literatura brasileira contemporânea',44,'LBC',null,null,null),
('joao ternura','João Ternura','Aníbal Machado','Literatura brasileira contemporânea',45,'LBC',null,null,null),
('lisboa: um sonho, um pesadelo','Lisboa: Um sonho, Um Pesadelo','Regina Drummond e Regina Rios','Literatura brasileira contemporânea',46,'LBC',null,null,null),
('longe das aldeias','Longe das Aldeias','Robertson Frizero','Literatura brasileira contemporânea',47,'LBC',null,null,null),
('mare nostrum','Mare Nostrum','Fabio Atui','Literatura brasileira contemporânea',48,'LBC',null,null,null),
('marie curie no pais da ciencia','Marie Curie No País da Ciência','Irène Cohen-Janca','Literatura brasileira contemporânea',49,'LBC',null,null,null),
('martini seco','Martini Seco','Fernando Sabino','Literatura brasileira contemporânea',50,'LBC',null,null,null),
('me liga!','Me Liga!','Flavia Bastos','Literatura brasileira contemporânea',51,'LBC',null,null,null),
('meus desacontecimentos - a historia da minha vida com palavras','Meus desacontecimentos - a história da minha vida com palavras','Eliane Brum','Literatura brasileira contemporânea',52,'LBC',null,null,null),
('minha primeira vez','Minha Primeira Vez','Luiz Ruffato','Literatura brasileira contemporânea',53,'LBC',null,null,null),
('morada das lembrancas','Morada das Lembranças','Daniela Bauer','Literatura brasileira contemporânea',54,'LBC',null,null,null),
('nada digo de ti, que em ti nao veja','Nada digo de ti, que em ti não veja','Eliana Alves Cruz','Literatura brasileira contemporânea',55,'LBC',null,null,null),
('nove, novena','Nove, novena','Osman Lins','Literatura brasileira contemporânea',56,'LBC',null,null,null),
('o amanauense belmiro','O amanauense Belmiro','Cyro dos Anjos','Literatura brasileira contemporânea',57,'LBC',null,null,null),
('o arroz de palma','O Arroz de Palma','Francisco Azevedo','Literatura brasileira contemporânea',58,'LBC',null,null,null),
('o ato e o fato','O ato e o fato','Carlos Heitor Cony','Literatura brasileira contemporânea',59,'LBC',null,null,null),
('o campo de batalha','O Campo de Batalha','Aldri Anunciação','Literatura brasileira contemporânea',60,'LBC',null,null,null),
('o cidadao incomum','O Cidadão Incomum','Pedro Ivo','Literatura brasileira contemporânea',61,'LBC',null,null,null),
('o delicado abismo da loucura','O delicado abismo da loucura','Raimundo Carrero','Literatura brasileira contemporânea',62,'LBC',null,null,null),
('o grumete e o tupinamba','O Grumete e  o Tupinambá','Adriano Messias','Literatura brasileira contemporânea',63,'LBC',null,null,null),
('o homem feito','O Homem Feito','Fernando Sabino','Literatura brasileira contemporânea',64,'LBC',null,null,null),
('o homem que calculava','O Homem que calculava','Malba Tahan','Literatura brasileira contemporânea',65,'LBC',null,null,null),
('o outro gume da faca','O Outro Gume da Faca','Fernando Sabino','Literatura brasileira contemporânea',66,'LBC',null,null,null),
('o peso da luz','O Peso da Luz','Ana Miranda','Literatura brasileira contemporânea',67,'LBC',null,null,null),
('o pior dia de todos','O Pior Dia de Todos','Daniela Kopsch','Literatura brasileira contemporânea',68,'LBC',null,null,null),
('o sedutor do sertao','O Sedutor do Sertão','Ariano Suassuna','Literatura brasileira contemporânea',69,'LBC',null,null,null),
('o selvagem da opera','O selvagem da ópera','Rubem Fonseca','Literatura brasileira contemporânea',70,'LBC',null,null,null),
('o tronco','O Tronco','Bernardo Élis','Literatura brasileira contemporânea',71,'LBC',null,null,null),
('o zahir','O Zahir','Paulo Coelho','Literatura brasileira contemporânea',72,'LBC',null,null,null),
('os caminhos de carla','Os Caminhos de Carla','Neir Ilelis','Literatura brasileira contemporânea',73,'LBC',null,null,null),
('os rios turvos','Os Rios Turvos','Luzilá Gonçalves Ferreira','Literatura brasileira contemporânea',74,'LBC',null,null,null),
('papel manteiga para embrulhar segredos','Papel Manteiga para embrulhar segredos','Cris Lisboa e Tato Tamberg','Literatura brasileira contemporânea',75,'LBC',null,null,null),
('pedro e ines de castro - uma historia de amor e guerra','Pedro e Inês de Castro - Uma História de Amor e Guerra','Helena Gomes','Literatura brasileira contemporânea',76,'LBC',null,null,null),
('pena de ganso','Pena de Ganso','Nilma Lacerda','Literatura brasileira contemporânea',77,'LBC',null,null,null),
('petrolina','Petrolina','Carlos Eduardo de Magalhães','Literatura brasileira contemporânea',78,'LBC',null,null,null),
('pra onde vao os dias que passam?','Pra onde vão os dias que passam?','Anna Claudia Ramos','Literatura brasileira contemporânea',79,'LBC',null,null,null),
('primerias estorias','Primerias estórias','Guimarães Rosa','Literatura brasileira contemporânea',80,'LBC',null,null,null),
('quando somos todos quase','Quando somos todos Quase','Manuel Filho','Literatura brasileira contemporânea',81,'LBC',null,null,null),
('quando tudo muda','Quando tudo muda','Regina Drummond','Literatura brasileira contemporânea',82,'LBC',null,null,null),
('quase memoria','Quase Memória','Carlos Heitor Cony','Literatura brasileira contemporânea',83,'LBC',null,null,null),
('quatro dias na vida de joel','Quatro dias na vida de Joel','Victor Vasconcelos','Literatura brasileira contemporânea',84,'LBC',null,null,null),
('quem chamarei de lar?','Quem chamarei de lar?','Myrriam Scotti','Literatura brasileira contemporânea',85,'LBC',null,null,null),
('quinze dias','Quinze Dias','Vítor Martins','Literatura brasileira contemporânea',86,'LBC',null,null,null),
('reflexoes refletidas','Reflexões Refletidas','Neir Ilelis','Literatura brasileira contemporânea',87,'LBC',null,null,null),
('relembro- tramas em familia','Relembro- Tramas em Família','Bibi da Pieve','Literatura brasileira contemporânea',88,'LBC',null,null,null),
('ruina y leveza','Ruína Y Leveza','Júlia Dantas','Literatura brasileira contemporânea',89,'LBC',null,null,null),
('sangue azul','Sangue Azul','Ana Carolina Delmas','Literatura brasileira contemporânea',90,'LBC',null,null,null),
('sofia','Sofia','Sidney Rocha','Literatura brasileira contemporânea',91,'LBC',null,null,null),
('sombras de reis barbudos','Sombras de Reis Barbudos','José J. Veiga','Literatura brasileira contemporânea',92,'LBC',null,null,null),
('sortes de villamor','Sortes de Villamor','Nilma Lacerda','Literatura brasileira contemporânea',93,'LBC',null,null,null),
('tilhas de leo - uma jornada musical','Tilhas de Léo - uma jornada musical','Ricardo Prado','Literatura brasileira contemporânea',94,'LBC',null,null,null),
('tomoromu - a arvore do mundo','TOMOROMU - A Árvore do Mundo','Cristino Wapichana','Literatura brasileira contemporânea',95,'LBC',null,null,null),
('torto arado','Torto Arado','Itamar Vieira Jr.','Literatura brasileira contemporânea',96,'LBC',null,null,null),
('trago na boca a memoria do meu fim','Trago Na Boca A Memória do Meu Fim','Ricardo Azevedo','Literatura brasileira contemporânea',97,'LBC',null,null,null),
('travessia - memorial de um contador de historias','Travessia - memorial de um contador de histórias','Franciscio Gregório da Silva Filho','Literatura brasileira contemporânea',98,'LBC',null,null,null),
('tudo ao mesmo tempo agora','Tudo Ao Mesmo Tempo Agora','Ana Maria Machado','Literatura brasileira contemporânea',99,'LBC',null,null,null),
('uma cancao pra voce','Uma canção pra você','Luiza Trigo','Literatura brasileira contemporânea',100,'LBC',null,null,null),
('vai encarar?','Vai Encarar?','Manuel Filho','Literatura brasileira contemporânea',101,'LBC',null,null,null),
('price and prejudice','Price and prejudice','Jane Austen','Literatura estrangeira',1,'LE',null,null,null),
('encontrando a liberdade','Encontrando a Liberdade','Jarvis Jay Masters','Literatura estrangeira',2,'LE',null,null,null),
('monstro','Monstro','Walter Dean Myers','Literatura estrangeira',3,'LE',null,null,null),
('o retrato de dorian gray','O retrato de Dorian Gray','Oscar Wilde','Literatura estrangeira',4,'LE',null,null,null),
('robinson crusoe','Robinson Crusoé','Daniel Defoe','Literatura estrangeira',5,'LE',null,null,null),
('o medico e o monstro','O Médico e o Monstro','Robert Louis Stevenson','Literatura estrangeira',6,'LE',null,null,null),
('a mulher de pes descalcos','A mulher de pés descalços','Scholastique Mukasonga','Literatura estrangeira',7,'LE',null,null,null),
('os piratas fantasmas','Os piratas fantasmas','William Hope Hodgson','Literatura estrangeira',8,'LE',null,null,null),
('o cao dos baskervilles','O Cão dos Baskervilles','Arthur Conan Doyle','Literatura estrangeira',9,'LE',null,null,null),
('no fundo do poco','No fundo do poço','Buchi Emechetta','Literatura estrangeira',10,'LE',null,null,null),
('irmaos para sempre','Irmãos para sempre','Chiara Lossani','Literatura estrangeira',11,'LE',null,null,null),
('cartas a uma negra','Cartas a uma negra','Françoise Ega','Literatura estrangeira',12,'LE',null,null,null),
('qual o problema das mulheres?','Qual o problema das mulheres?','Jacky Fleming','Literatura estrangeira',13,'LE',null,null,null),
('dracula''s quest','Dracula''s Quest','Bram Stocker','Literatura estrangeira',14,'LE',null,null,null),
('a armadilha','A Armadilha','Emmanuel Boe','Literatura estrangeira',15,'LE',null,null,null),
('passando-se','Passando-se','Nella Larsen','Literatura estrangeira',16,'LE',null,null,null),
('viagem em volta do meu quarto','Viagem em volta do meu quarto','Xavier de Maistre','Literatura estrangeira',17,'LE',null,null,null),
('cyrano de bergerac','Cyrano de Bergerac','Edmond Rostand','Literatura estrangeira',18,'LE',null,null,null),
('a mascara da morte rubra','A Máscara da Morte Rubra','Edgard Allan Poe','Literatura estrangeira',19,'LE',null,null,null),
('anne de green gables','Anne de Green Gables','Lucy Maud Montgomery','Literatura estrangeira',20,'LE',null,null,null),
('a revolucao dos bichos','A Revolução dos Bichos','George Orwell','Literatura estrangeira',21,'LE',null,null,null),
('dez dias no manicomio','Dez dias no manicômio','Nellie Blye','Literatura estrangeira',22,'LE',null,null,null),
('incidentes da vida de uma escrava','Incidentes da vida de uma escrava','Harriet Ann Jacobs','Literatura estrangeira',23,'LE',null,null,null),
('eu, minha irmae seu universo particular','Eu, minha irmãe seu universo particular','Eileen Garvin','Literatura estrangeira',24,'LE',null,null,null),
('sob o por do sol','Sob o pôr do sol','Bram Stocker','Literatura estrangeira',25,'LE',null,null,null),
('admiravel mundo novo','Admirável mundo novo','Aldous Huxley','Literatura estrangeira',26,'LE',null,null,null),
('dois hussardos','Dois Hussardos','Lev Tolstói','Literatura estrangeira',27,'LE',null,null,null),
('a mercadoria mais preciosa','A mercadoria mais preciosa','Jean-Claude Grumberg','Literatura estrangeira',28,'LE',null,null,null),
('popol vuh','Popol Vuh','Josely Vianna Baptista','Literatura estrangeira',29,'LE',null,null,null),
('batendo a porta do ceu','Batendo à porta do céu','Jordi Sierra i Fabri','Literatura estrangeira',30,'LE',null,null,null),
('a ultima mensagem de hiroshima','A última mensagem de Hiroshima','Takashi Morita','Literatura estrangeira',31,'LE',null,null,null),
('narrativa de william wells brown, escravo fugitivo','Narrativa de William Wells Brown, Escravo Fugitivo','William Wells Brown','Literatura estrangeira',32,'LE',null,null,null),
('a teoria do iceberg','A Teoria do Iceberg','Christopher Bouix','Literatura estrangeira',33,'LE',null,null,null),
('a estrada enluarada e outras historias','A estrada enluarada e outras histórias','Ambrose Pierce','Literatura estrangeira',34,'LE',null,null,null),
('a historiade mary prince - uma escrava das indias ocidentais','A Históriade Mary Prince - Uma escrava das Índias Ocidentais','Mary Price','Literatura estrangeira',35,'LE',null,null,null),
('um rio chamado tempo, uma casa chamada terra','Um Rio Chamado Tempo, Uma Casa Chamada Terra','Mia Couto','Literatura estrangeira',36,'LE',null,null,null),
('a casa assombrada e outros contos de horror','A Casa Assombrada e outros contos de horror','Edith Nesbit','Literatura estrangeira',37,'LE',null,null,null),
('o hobbit','O Hobbit','J.R.R. Tolkien','Literatura estrangeira',38,'LE',null,null,null),
('romeu e julieta','Romeu e Julieta','William Shakespeare','Literatura estrangeira',39,'LE',null,null,null),
('contos russos juvenis','Contos Russos Juvenis','Vários Autores','Literatura estrangeira',40,'LE',null,null,null),
('the masque of the read death','The Masque of the read death','Edgard Allan Poe','Literatura estrangeira',41,'LE',null,null,null),
('a outra face','A outra face','Deborach Ellis','Literatura estrangeira',42,'LE',null,null,null),
('pantera no porao','Pantera no porão','Amós Oz','Literatura estrangeira',43,'LE',null,null,null),
('poliana cresceu','Poliana cresceu','Eleanor H. Porter','Literatura estrangeira',44,'LE',null,null,null),
('carta a minha filha','Carta a minha filha','Maya Angelou','Literatura estrangeira',45,'LE',null,null,null),
('fahrenheit 451','Fahrenheit 451','Ray Bradbury','Literatura estrangeira',46,'LE',null,null,null),
('longa petala de mar','Longa Pétala de Mar','Isabel Allende','Literatura estrangeira',47,'LE',null,null,null),
('stephen heroi','Stephen Herói','James Joyce','Literatura estrangeira',48,'LE',null,null,null),
('preco de noiva','Preço de Noiva','Buchi Emechetta','Literatura estrangeira',49,'LE',null,null,null),
('as feras cumplices','As Feras Cúmplices','Horacio Quiroga','Literatura estrangeira',50,'LE',null,null,null),
('mundo de sofia - romance da historia da filosofia','Mundo de Sofia - Romance Da História Da Filosofia','Jostein Gaarden','Literatura estrangeira',51,'LE',null,null,null),
('memorias de um adolescente brasileiro na alemanha nazista','Memórias de um Adolescente Brasileiro na Alemanha Nazista','Elisabeth Loibl','Literatura estrangeira',52,'LE',null,null,null),
('o mundo de anne frank - la fora, a guerra','O mundo de Anne Frank - Lá fora, a guerra','Janny van der Molen','Literatura estrangeira',54,'LE',null,null,null),
('os meninos que enganavam nazistas','Os Meninos que Enganavam Nazistas','Joseph Joffo','Literatura estrangeira',56,'LE',null,null,null),
('diarios deraqqa','Diários deRaqqa','Samer','Literatura estrangeira',58,'LE',null,null,null),
('o diario de anne frank','O Diário de Anne Frank','Anne Frank','Literatura estrangeira',59,'LE',null,null,null),
('holy cow - uma fabula animal','Holy Cow - Uma Fábula Animal','Duchovny','Literatura estrangeira',60,'LE',null,null,null),
('a esperanca e uma torta de maca','A esperança é uma torta de maçã','Sarah Moore Fitzgerald','Literatura estrangeira',61,'LE',null,null,null),
('confissoes de um amigo imaginario','Confissões de um Amigo Imaginário','Michelle Cuevas','Literatura estrangeira',62,'LE',null,'Rosa','#ec4899'),
('os caras malvados','Os Caras Malvados','Aaron Blabey','Literatura estrangeira',63,'LE',null,null,null),
('anne frank - a memoria do holocausto','Anne Frank - A memória do Holocausto','Eduardo Alonso','Literatura estrangeira',64,'LE',null,null,null),
('around the world in eighty days','Around The World In Eighty Days','Jules Verne','Literatura estrangeira',65,'LE',null,null,null),
('uma travessia perigosa','Uma Travessia Perigosa','Jane Mitchell','Literatura estrangeira',66,'LE',null,null,null),
('a mala de hana - uma historia real','A mala de Hana - uma história real','Karen Levine','Literatura estrangeira',67,'LE',null,null,null),
('muito longe de casa - memorias de um menino-soldado','Muito longe de casa - Memórias de um Menino-Soldado','Isabel Allende','Literatura estrangeira',68,'LE',null,null,null),
('o homem que plantava arvores','O Homem Que Plantava Árvores','Jean Giono','Literatura estrangeira',69,'LE',null,null,null),
('a botija','A Botija','Clotilde Tavares','Literatura juvenil',1,'LJ','6V','Verde','#16a34a'),
('a alma do urso','A Alma do Urso','Gustavo Bernardo','Literatura juvenil',2,'LJ','6V','Laranja','#f59e0b'),
('a cancao de monalisa','A canção de Monalisa','Helena Gomes','Literatura juvenil',3,'LJ','6V','Verde','#16a34a'),
('a culpa e toda de marte!','A culpa é toda de marte!','Paula Browne','Literatura juvenil',4,'LJ','6V','Verde','#16a34a'),
('a declaracao','A Declaração','Michaël Escoffier e Stéphane Sénégas','Literatura juvenil',5,'LJ','6V','Verde','#16a34a'),
('a fabrica de nuvem','A fábrica de nuvem','Jordi Sierra i Fabra','Literatura juvenil',6,'LJ','6V',null,null),
('a fabulosa morte do professor de portugues','A Fabulosa Morte do Professor de Português','Lourenço Cazarré','Literatura juvenil',7,'LJ','6R','Rosa','#ec4899'),
('a fazenda distante','A fazenda distante','Pierre-Marie Beaude','Literatura juvenil',8,'LJ','6V','Verde','#16a34a'),
('a festa das letras','A Festa das Letras','Josué de Castro','Literatura juvenil',9,'LJ','6R','Rosa','#ec4899'),
('a geringonca','A geringonça','Gabriel de Matos','Literatura juvenil',10,'LJ','6V','Verde','#16a34a'),
('a grande roda de historias','A Grande Roda de Histórias','Nélio Spréa e Milton Karam','Literatura juvenil',11,'LJ','6R','Rosa','#ec4899'),
('a historia de clarice','A História de Clarice','Anna Claudia Ramos','Literatura juvenil',12,'LJ','6V','Verde','#16a34a'),
('a iliada e o premio','A Ilíada e O Prêmio','Sonia Rodrigues','Literatura juvenil',13,'LJ','6L',null,null),
('a lenda de abelardo','A Lenda de Abelardo','Dionísio Jacob','Literatura juvenil',14,'LJ','6V','Laranja','#f59e0b'),
('a lingua de fora','A língua de fora','Juva Batella','Literatura juvenil',15,'LJ','6V','Verde','#16a34a'),
('a mae e o filho da mae & a maquina de fazer amor','A Mãe E O Filho Da Mãe & A Máquina de fazer Amor','Wander Piroli','Literatura juvenil',16,'LJ','6V','Verde','#16a34a'),
('a menina que colecionava borboletas','A menina que colecionava BORBOLETAS','Bruna Vieira','Literatura juvenil',17,'LJ','6V','Verde','#16a34a'),
('a roda do vento','A Roda do Vento','Nélida Piñon','Literatura juvenil',18,'LJ','6R','Verde','#16a34a'),
('a senhora da serra','A Senhora da Serra','Virgilio Moretzshon','Literatura juvenil',19,'LJ','6V','Verde','#16a34a'),
('a senhora dos animais','A Senhora dos Animais','Vinicius Caldevilla','Literatura juvenil',20,'LJ','6V','Verde','#16a34a'),
('a sobrinha do poeta','A sobrinha do poeta','Maria Valéria Rezende','Literatura juvenil',21,'LJ','6V','Verde','#16a34a'),
('a vida naquela hora','A vida naquela hora','João Anzanello Carrascoza','Literatura juvenil',22,'LJ','6V','Verde','#16a34a'),
('a vinganca do indio cavaleiro','A vingança do Índio Cavaleiro','José Hamilton Ribeiro','Literatura juvenil',23,'LJ','6V','Verde','#16a34a'),
('abraao e as frutas','Abraão e as frutas','Luciana V.P. de Mendonça','Literatura juvenil',24,'LJ','6A','Amarela','#eab308'),
('adeus e para super-herois','Adeus é para super-heróis','Isabela Noronha','Literatura juvenil',25,'LJ','6V','Verde','#16a34a'),
('adolescencia','Adolescência','Guila Azevedo','Literatura juvenil',26,'LJ','6V','Laranja','#f59e0b'),
('adoraveis vigaristas','Adoráveis Vigaristas','Ganymédes José','Literatura juvenil',27,'LJ','6R','Rosa','#ec4899'),
('agua luminosa','Água Luminosa','Domingos Pellegrini','Literatura juvenil',28,'LJ','6V','Verde','#16a34a'),
('amazonas - patria da agua','Amazonas - Pátria da Água','Thiago de Mello','Literatura juvenil',29,'LJ','6V','Verde','#16a34a'),
('amor & cuba-libre','Amor & Cuba-libre','Álvaro Cardoso Gomes','Literatura juvenil',30,'LJ','6V','Verde','#16a34a'),
('ana levada da brega','Ana Levada da Brega','Maria de Lourdes Krieger','Literatura juvenil',31,'LJ','6V',null,null),
('antes da meia-noite','Antes da meia-noite','Menalton Braff','Literatura juvenil',32,'LJ','6V','Laranja','#f59e0b'),
('apatica','Apática','Marcelo Xavier','Literatura juvenil',33,'LJ','6V','Verde','#16a34a'),
('arqueologo do futuro','Arqueólogo do Futuro','Maria Valéria Rezende','Literatura juvenil',34,'LJ','6V','Verde','#16a34a'),
('artes e oficios','Artes e Ofícios','Roseana Kligerman Murray','Literatura juvenil',35,'LJ','6L','Laranja','#f59e0b'),
('as artimanhas do napoleao e outras batalhas cotidianas','As artimanhas do Napoleão e outras batalhas cotidianas','Antonio Cestaro','Literatura juvenil',36,'LJ','6V','Verde','#16a34a'),
('as incriveis aventuras e estranhos infortunios de anthony knivet','As Incríveis Aventuras e Estranhos Infortúnios de Anthony Knivet','Anthony Knivet','Literatura juvenil',37,'LJ','6V','Verde','#16a34a'),
('ataque do comando p.q.','Ataque do Comando P.Q.','Moacyr Scliar','Literatura juvenil',39,'LJ','6V','Verde','#16a34a'),
('authentic games - a batalha da torre','AUTHENTIC GAMES - A Batalha da Torre','Marco Tulio','Literatura juvenil',40,'LJ','6A',null,null),
('authentic games - vivendo uma vida autentica','AUTHENTIC GAMES - Vivendo Uma Vida Autêntica','Marco Tulio','Literatura juvenil',41,'LJ','6A',null,null),
('autobiografia de um super-heroi','Autobiografia de um super-herói','Alexandre Barbosa de Souza','Literatura juvenil',42,'LJ','6V','Verde','#16a34a'),
('ave do paraiso','Ave do Paraíso','Georgina Martins','Literatura juvenil',43,'LJ','6V','Verde','#16a34a'),
('aventuras de pedro malasartes','Aventuras de Pedro Malasartes','Nelson Abissú','Literatura juvenil',44,'LJ','6V','Verde','#16a34a'),
('batata cozida, mingau de cara','Batata cozida, mingau de cará','Eloí Elisabete','Literatura juvenil',45,'LJ','6A','Amarela','#eab308'),
('beto, o analfabeto','Beto, o Analfabeto','Drummond Amorim','Literatura juvenil',46,'LJ','6V','Verde','#16a34a'),
('borboletas na chuva','Borboletas na chuva','Neusa Sorrenti','Literatura juvenil',47,'LJ','6V','Verde','#16a34a'),
('brincadeira mortal','Brincadeira Mortal','Pedro Bandeira','Literatura juvenil',48,'LJ','6R','Rosa','#ec4899'),
('bumba na farra do boi','Bumba na Farra do Boi','Gilberto Braga de Melo','Literatura juvenil',49,'LJ','6V','Verde','#16a34a'),
('cabelos de fogo, olhos de agua','Cabelos de fogo, olhos de água','Angela Leite e Lino de Albergaria','Literatura juvenil',50,'LJ','6V','Verde','#16a34a'),
('cabelos molhados','Cabelos molhados','Luís Pimentel','Literatura juvenil',51,'LJ','6A','Amarela','#eab308'),
('cacada','CAÇADA','Fernando Vilela','Literatura juvenil',52,'LJ','6V','Laranja','#f59e0b'),
('cafe van gogh','Café Van Gogh','Cynthia Rylant','Literatura juvenil',53,'LJ','6V','Laranja','#f59e0b'),
('cantigas de adolescer','Cantigas de Adolescer','Elias José','Literatura juvenil',54,'LJ','6L','Laranja','#f59e0b'),
('caos na escola','Caos na Escola','Christian David','Literatura juvenil',55,'LJ','6V','Verde','#16a34a'),
('cara ou cora?','Cara ou cora?','Fernando Sabino','Literatura juvenil',56,'LJ','6V',null,null),
('cara senhora minha avo','Cara Senhora minha avó','Elisabeth Brami','Literatura juvenil',57,'LJ','6R',null,null),
('caravela','Caravela','Gabriel Bicalho','Literatura juvenil',58,'LJ','6A','Amarela','#eab308'),
('chica, sinha!','Chica, Sinhá!','Carlos Alberto de Carvalho','Literatura juvenil',59,'LJ','6V','Verde','#16a34a'),
('chove na cidade','Chove na Cidade','Fernando A. Pires','Literatura juvenil',60,'LJ','6V','Verde','#16a34a'),
('chuva de letras','Chuva de LETRAS','Luís Alberto Brandão','Literatura juvenil',61,'LJ','6V','Verde','#16a34a'),
('clarice','Clarice','Rober Mello','Literatura juvenil',62,'LJ','6V','Verde','#16a34a'),
('cobras em compota','Cobras em compota','Índigo','Literatura juvenil',63,'LJ','6A','Amarela','#eab308'),
('comandante hussi','Comandante Hussi','Jorge Araújo e Pedro Sousa Pereira','Literatura juvenil',64,'LJ','6V','Verde','#16a34a'),
('companhia tres marias','Companhia Três Marias','Maria Amália Camargo','Literatura juvenil',65,'LJ','6V','Verde','#16a34a'),
('confusoes de um garoto','Confusões de um Garoto','Patrícia Barboza','Literatura juvenil',67,'LJ','6A','Amarela','#eab308'),
('de cabeca baixa','De cabeça baixa','Mirna Pinsky','Literatura juvenil',68,'LJ','6V','Verde','#16a34a'),
('de mim ja nem se lembra','De mim já nem se lembra','Luiz Ruffato','Literatura juvenil',69,'LJ','6V','Verde','#16a34a'),
('de olho nas penas','De olho nas penas','Ana Marida Machado','Literatura juvenil',70,'LJ','6V','Verde','#16a34a'),
('desenhos de guerra e de amor','Desenhos de Guerra e de amor','Flávio de Souza','Literatura juvenil',71,'LJ','6R',null,null),
('dia de sao nunca a tarde','Dia de São Nunca à Tarde','Roberto Drummond','Literatura juvenil',72,'LJ','6V','Verde','#16a34a'),
('diario de um zumbi do minecraft - um desafio assustador','DIÁRIO de um ZUMBI do MINECRAFT - Um desafio assustador','Herobrine Books','Literatura juvenil',73,'LJ','6L',null,null),
('dinheiro do ceu','Dinheiro do Céu','Marcos Rey','Literatura juvenil',74,'LJ','6V','Verde','#16a34a'),
('dois passaros. e o voo arcanjo','Dois pássaros. E o vôo arcanjo','Nilma Gonçalves Lacerda','Literatura juvenil',75,'LJ','6V','Verde','#16a34a'),
('emil e os tres gemeos','Emil e os três gêmeos','Erich Kästner','Literatura juvenil',76,'LJ','6R','Rosa','#ec4899'),
('enigma na capela real','Enigma na Capela Real','Ana Cristina Massa','Literatura juvenil',77,'LJ','6V','Verde','#16a34a'),
('enquanto aurora - momentos de uma infancia brasileira','Enquanto aurora - momentos de uma infância brasileira','Margarida Patriota','Literatura juvenil',78,'LJ','6V','Verde','#16a34a'),
('entre as junturas dos ossos','Entre as junturas dos ossos','Vera Lúcia de Oliveira','Literatura juvenil',79,'LJ','6A','Amarela','#eab308'),
('entre silencios e gestos','Entre Silêncios e Gestos','Marcos Arthur','Literatura juvenil',80,'LJ','6R','Rosa','#ec4899'),
('escola da fama - alcancando as estrelas','ESCOLA DA FAMA - Alcançando as Estrelas','Cindy Jefferies','Literatura juvenil',81,'LJ','6A','Amarela','#eab308'),
('escola da fama - rivais','ESCOLA DA FAMA - Rivais','Cindy Jefferies','Literatura juvenil',82,'LJ','6A','Amarela','#eab308'),
('escola da fama - uma nova estrela','ESCOLA DA FAMA - Uma Nova Estrela','Cindy Jefferies','Literatura juvenil',83,'LJ','6A','Amarela','#eab308'),
('eu me chamo antonio','Eu me chamo Antônio','Pedro Gabriel','Literatura juvenil',84,'LJ','6V','Verde','#16a34a'),
('familia composta','Família Composta','Domingos Pellegrini','Literatura juvenil',85,'LJ','6A','Amarela','#eab308'),
('filandras','Filandras','Adélia Prado','Literatura juvenil',86,'LJ','6V','Verde','#16a34a'),
('filho de peixe','Filho de Peixe','Marcelo Carneiro da Cunha','Literatura juvenil',87,'LJ','6R','Rosa','#ec4899'),
('finnicio riovem','Finnício Riovém','Donaldo Schüler','Literatura juvenil',88,'LJ','6V','Verde','#16a34a'),
('furos','Furos','Cècile Bergame e Aude Léonard','Literatura juvenil',89,'LJ','6V','Verde','#16a34a'),
('godi um menino chamado liberdade','Godi um menino chamado liberdade','Fábio Ferreira','Literatura juvenil',90,'LJ','6V',null,null),
('gotham sampa city','Gotham Sampa City','Eduardo Zaigab','Literatura juvenil',91,'LJ','6V','Verde','#16a34a'),
('gravida aos 14 anos?','Grávida aos 14 anos?','Guila Azevedo','Literatura juvenil',92,'LJ','6L','Laranja','#f59e0b'),
('historias bem-contadas','Histórias Bem-Contadas','Marcia Paganini','Literatura juvenil',93,'LJ','6V',null,null),
('historias da nossa gente','Histórias da Nossa Gente','Sandra Lane','Literatura juvenil',94,'LJ','6V','Verde','#16a34a'),
('historias da pre-historia','Histórias da Pré-História','Alberto Moravia','Literatura juvenil',95,'LJ','6V','Verde','#16a34a'),
('historias de antigamente','Histórias de Antigamente','Patricia Averbach','Literatura juvenil',96,'LJ','6R','Rosa','#ec4899'),
('janela magica','Janela mágica','Cecília Meirelles','Literatura juvenil',97,'LJ','6V','Verde','#16a34a'),
('joao e maria e outros de grimm','João e Maria e outros de Grimm','Jaco e Wilhelm Grimm','Literatura juvenil',98,'LJ','6V',null,null),
('joias de familia','Jóias de Família','Zulmira Ribeiro Tavares','Literatura juvenil',99,'LJ','6V','Verde','#16a34a'),
('leo, o pardo','Léo, o pardo','Rinaldo Santos','Literatura juvenil',100,'LJ','6A','Amarela','#eab308'),
('lola e ervilha','Lola e Ervilha','Annette Mierswa','Literatura juvenil',101,'LJ','6R','Rosa','#ec4899'),
('longe dos olhos','Longe dos Olhos','Ivan Jaf','Literatura juvenil',102,'LJ','6V','Verde','#16a34a'),
('luciola em cordel','Lucíola em Cordel','Marco Haurélio','Literatura juvenil',103,'LJ','6V','Verde','#16a34a'),
('madalena','Madalena','Cristiane Dantas','Literatura juvenil',104,'LJ','6A','Amarela','#eab308'),
('manual do defensor do planeta','Manual do Defensor do Planeta','João Alegria','Literatura juvenil',105,'LJ','6R','Rosa','#ec4899'),
('margarida, a fada dos sonhos (fadas brilhantes e fascinantes)','Margarida, a Fada dos Sonhos (FADAS BRILHANTES E FASCINANTES)','Moira Buttefield','Literatura juvenil',106,'LJ','6A',null,null),
('maria antonieta e o gnomo','Maria Antonieta e o Gnomo','Índigo','Literatura juvenil',107,'LJ','6R','Rosa','#ec4899'),
('marieta tem um dilema','Marieta tem um dilema','Martine Murray','Literatura juvenil',108,'LJ','6V','Verde','#16a34a'),
('mastigando humanos - um romance psicologico','Mastigando Humanos - um romance psicológico','Santiago Nazarian','Literatura juvenil',109,'LJ','6V','Verde','#16a34a'),
('mendix o ladrao de historias','MENDIX O Ladrão de Histórias','Breno Fernandes','Literatura juvenil',110,'LJ','6R',null,null),
('meninos da planicie','Meninos da Planície','Cástor Cartelle','Literatura juvenil',111,'LJ','6L','Verde','#16a34a'),
('meninos do farol','Meninos do Farol','Raul Drewnick','Literatura juvenil',112,'LJ','6V','Laranja','#f59e0b'),
('meu outro eu','Meu Outro Eu','Marcelo Duarte','Literatura juvenil',113,'LJ','6V','Laranja','#f59e0b'),
('meu pai nao mora mais aquilo','Meu Pai Não Mora Mais Aquilo','Caio Riter','Literatura juvenil',114,'LJ','6V',null,null),
('minha vida nao e cor-de-rosa','Minha vida não é cor-de-rosa','Penélope Martins','Literatura juvenil',115,'LJ','6V','Verde','#16a34a'),
('minhas assombracoes','Minhas assombrações','Angela-Lago','Literatura juvenil',116,'LJ','6V','Verde','#16a34a'),
('minhas ferias, pula uma linha, paragrafo.','Minhas férias, pula uma linha, parágrafo.','Christiane Gribel','Literatura juvenil',117,'LJ','6V',null,null),
('moby dick','Moby Dick','Herman Melville','Literatura juvenil',118,'LJ','6V','Verde','#16a34a'),
('molecagem','Molecagem','Luiz Claudio Cardoso','Literatura juvenil',119,'LJ','6V','Verde','#16a34a'),
('nadando contra a morte','Nadando contra a morte','Lourenço Cazarré','Literatura juvenil',120,'LJ','6V','Verde','#16a34a'),
('negocios de familia - conversa de velorio','Negócios de Família - Conversa de Velório','Domingos Pellegrini','Literatura juvenil',121,'LJ','6V','Verde','#16a34a'),
('no tempo dos dinossauros','No Tempo dos Dinossauros','Álvaro Cardoso Gomes','Literatura juvenil',122,'LJ','6L','Verde','#16a34a'),
('nos 4','Nós 4','João Anzanello Carrascoza','Literatura juvenil',123,'LJ','6V','Verde','#16a34a'),
('novas historias antigas','Novas Histórias Antigas','Rosane Pamplona','Literatura juvenil',124,'LJ','6V','Verde','#16a34a'),
('nunca serei um super-heroi','Nunca Serei Um Super-Herói','Antonio Santa Ana','Literatura juvenil',125,'LJ','6V','Verde','#16a34a'),
('o agito de pilar no egito','O Agito de Pilar no Egito','Flávia Lins e Silva','Literatura juvenil',126,'LJ','6V','Verde','#16a34a'),
('o amo e um passaro vermelho','O amo é um pássaro vermelho','Lucília Junqueira de Almeida Prado','Literatura juvenil',127,'LJ','6V',null,null),
('o anjo linguarido','O Anjo Linguarido','Walcyr Carrasco','Literatura juvenil',128,'LJ','6V',null,null),
('o barqueiro e o canoeiro','O barqueiro e o canoeiro','Fernando Vilela','Literatura juvenil',129,'LJ','6V','Verde','#16a34a'),
('o bau do tio quim','O Baú do Tio Quim','Luiz Antonio Aguiar','Literatura juvenil',130,'LJ','6V','Verde','#16a34a'),
('o canario e o manequim','O canário e o Manequim','Walmir Ayala','Literatura juvenil',131,'LJ','6V','Laranja','#f59e0b'),
('o carrasco que era santo','O Carrasco que era Santo','Josué Montello','Literatura juvenil',132,'LJ','6V','Verde','#16a34a'),
('o caso do filho do encadernador','O Caso do Filho do Encadernador','Marcos Rey','Literatura juvenil',133,'LJ','6V','Verde','#16a34a'),
('o dia das maes','O Dia das Mães','Lino de Albergaria','Literatura juvenil',134,'LJ','6V','Verde','#16a34a'),
('o enigma das amazonas','O enigma das amazonas','Luiz Galdino','Literatura juvenil',135,'LJ','6R','Rosa','#ec4899'),
('o fazedor de velhos','O Fazedor de Velhos','Rodrigo Lacerda','Literatura juvenil',136,'LJ','6R','Rosa','#ec4899'),
('o forte','O Forte','Adoniasa Filho','Literatura juvenil',137,'LJ','6V','Verde','#16a34a'),
('o gato malhado e a andorinha sinha','O Gato Malhado e A Andorinha Sinhá','Jorge Amado','Literatura juvenil',138,'LJ','6V','Verde','#16a34a'),
('o gosto do apfelstrudel','O gosto do APFELSTRUDEL','Gustavo Bernardo','Literatura juvenil',139,'LJ','6A','Amarela','#eab308'),
('o grande desafio','O Grande Desafio','Pedro Bandeira','Literatura juvenil',140,'LJ','6R','Rosa','#ec4899'),
('o homem da arvore na cabeca','O Homem da árvore na cabeça','Celso Sisto','Literatura juvenil',141,'LJ','6V','Verde','#16a34a'),
('o jovem jk','O Jovem JK','Roniwalter Jatobá','Literatura juvenil',142,'LJ','6R','Rosa','#ec4899'),
('o leao da noite estrelada','O leão da noite estrelada','Ricardo Azevedo','Literatura juvenil',143,'LJ','6V','Verde','#16a34a'),
('o menino e o jegue','O Menino e o Jegue','Aristides Fraga Lima','Literatura juvenil',144,'LJ','6R','Rosa','#ec4899'),
('o menino negro','O Menino Negro','Camara Laye','Literatura juvenil',145,'LJ','6V','Verde','#16a34a'),
('o misterio da ilha','O mistério da ilha','Ana Maria Machado','Literatura juvenil',146,'LJ','6V','Verde','#16a34a'),
('o misterio do 5 estrelas','O Mistério do 5 Estrelas','Marcos Rey','Literatura juvenil',147,'LJ','6V','Verde','#16a34a'),
('o misterio dos morros dourados','O Mistério dos Morros Dourados','Francisco Marins','Literatura juvenil',148,'LJ','6R','Rosa','#ec4899'),
('o mundo de buster','O Mundo de Buster','Bjarne, Reuter','Literatura juvenil',149,'LJ','6V','Verde','#16a34a'),
('o mundo e pra ser voado','O mundo é pra ser voado','Vivina de Assis Viana','Literatura juvenil',150,'LJ','6V','Laranja','#f59e0b'),
('o nobre sequestrador','O Nobre Sequestrador','Antônio Torres','Literatura juvenil',151,'LJ','6V','Verde','#16a34a'),
('o outro apaixonado por marilia de dirceu','O outro apaixonado por Marília de Dirceu','Jair Vitória','Literatura juvenil',152,'LJ','6R','Rosa','#ec4899'),
('o panfeto - detetive siqueira','O Panfeto - Detetive Siqueira','Dionísio Jacob','Literatura juvenil',153,'LJ','6V',null,null),
('o peixe que podia cantar','O peixe que podia cantar','Ricardo Azevedo','Literatura juvenil',154,'LJ','6V','Verde','#16a34a'),
('o rapto do garoto de ouro','O Rapto do Garoto de Ouro','Marcos Rey','Literatura juvenil',155,'LJ','6V','Verde','#16a34a'),
('o risonho cavalo do principe','O Risonho Cavalo do Príncipe','Jose J. Veiga','Literatura juvenil',156,'LJ','6V','Verde','#16a34a'),
('o saci epaminondas','O Saci Epaminondas','Alan Oliveira','Literatura juvenil',157,'LJ','6V','Verde','#16a34a'),
('o segredo de rigoberta','O Segredo de Rigoberta','Raquel Martha Barthe','Literatura juvenil',158,'LJ','6R','Rosa','#ec4899'),
('o tesouro de olinda','O Tesouro de Olinda','Rogério Andrade Barbosa','Literatura juvenil',159,'LJ','6V','Verde','#16a34a'),
('o ultimo mamifero do martinelli','O último mamífero do Martinelli','Marcos Rey','Literatura juvenil',160,'LJ','6V','Verde','#16a34a'),
('o vale de solombra','O Vale de Solombra','Eustáquio Gomes','Literatura juvenil',161,'LJ','6V','Verde','#16a34a'),
('olhinhos de gato','Olhinhos de Gato','Cecília Meirelles','Literatura juvenil',162,'LJ','6V','Verde','#16a34a'),
('operacao strangelov','Operação Strangelov','Maria José de Queiroz','Literatura juvenil',163,'LJ','6V','Verde','#16a34a'),
('os cavalinhos de platiplanto','Os Cavalinhos de Platiplanto','Jose J. Veiga','Literatura juvenil',164,'LJ','6V','Verde','#16a34a'),
('oxente! a mulher enterrada viva','OXENTE! A Mulher Enterrada Viva','Toni Brandão','Literatura juvenil',165,'LJ','6R','Rosa','#ec4899'),
('papai urso','Papai Urso','Cecília Eudave','Literatura juvenil',166,'LJ','6V','Verde','#16a34a'),
('pe de guerra - memorias de uma menina na guerra da bahia','Pé de Guerra - Memórias de uma menina na guerra da Bahia','Sonia Robatto','Literatura juvenil',167,'LJ','6V','Verde','#16a34a'),
('perdidos no tempo','Perdidos no Tempo','Silvia La Regina','Literatura juvenil',168,'LJ','6R',null,null),
('por parte de pai','Por parte de PAI','Bartolomeu Campos de Queirós','Literatura juvenil',169,'LJ','6V','Verde','#16a34a'),
('por um mundo melhor','Por Um Mundo Melhor','Lannoy Dorin','Literatura juvenil',170,'LJ','6V','Verde','#16a34a'),
('praca das dores','Praça das Dores','José Louzeiro','Literatura juvenil',171,'LJ','6V','Verde','#16a34a'),
('quebra-nozes & camundongo rei','Quebra-Nozes & Camundongo Rei','E.T.A  Hoffman','Literatura juvenil',172,'LJ','6V','Verde','#16a34a'),
('redacoes perigosas ii - a fome','Redações perigosas II - A fome','Telma Guimarães Castro Andrade','Literatura juvenil',173,'LJ','6L','Laranja','#f59e0b'),
('rio liberdade - uma aventura no pantanal','Rio Liberdade - Uma aventura no Pantanal','Werner Zotz','Literatura juvenil',174,'LJ','6V','Verde','#16a34a'),
('se os tubaroes fossem homens','Se os tubarões fossem homens','Bertold Brecht','Literatura juvenil',175,'LJ','6V','Verde','#16a34a'),
('sundjata o principe leao','Sundjata O Príncipe Leão','Rogério Andrade Barbosa','Literatura juvenil',176,'LJ','6V','Verde','#16a34a'),
('tao longe tao perto','Tão Longe Tão Perto','Silvana de Menezes','Literatura juvenil',177,'LJ','6V','Verde','#16a34a'),
('tempo das cerejas','Tempo das Cerejas','Márcia Maia Conforti','Literatura juvenil',178,'LJ','6V','Verde','#16a34a'),
('tempo justo','Tempo Justo','João Anzanello Carrascoza','Literatura juvenil',179,'LJ','6V','Verde','#16a34a'),
('tubarao com a faca nas costas','Tubarão com a faca nas costas','Cezar Dias','Literatura juvenil',180,'LJ','6A','Amarela','#eab308'),
('turmas do predio, da rua e do bairro','Turmas do Prédio, da Rua e do Bairro','Léo Cunha e Ricardo Benevides','Literatura juvenil',181,'LJ','6V','Verde','#16a34a'),
('um lenco de infinitos fios','Um Lenço de Infinitos Fios','Susana Ventura','Literatura juvenil',182,'LJ','6V',null,null),
('um time muito especial','Um time muito especial','Jane Tutikian','Literatura juvenil',183,'LJ','6L','Laranja','#f59e0b'),
('vermelho amargo','Vermelho Amargo','Bartolomeu Campos de Queirós','Literatura juvenil',184,'LJ','6V','Verde','#16a34a'),
('vinculos','Vínculos','Lúcia Pimentel Góes','Literatura juvenil',185,'LJ','6R','Rosa','#ec4899'),
('diario de um zumbi de minecraft - um desafio assustador','DIÁRIO DE UM ZUMBI DE MINECRAFT - Um desafio assustador','Herobrine Books','Literatura juvenil',186,'LJ','6L','Laranja','#f59e0b'),
('autenthic games - a batalha da torre','Autenthic Games - A Batalha da torre','Marco Tulio','Literatura juvenil',187,'LJ','6L','Laranja','#f59e0b'),
('autenthic games- vivendo uma vida autentica','Autenthic Games- Vivendo Uma Vida Autêntica','Marco Tulio','Literatura juvenil',188,'LJ','6L','Laranja','#f59e0b'),
('o mar que nos abraca','O Mar que nos abraça','Marcus Vinicius Rodrigues','Contos',1,'CONT',null,null,null),
('contos satiricos do conselheiro xx','Contos Satíricos do Conselheiro XX','Humberto de Campos','Contos',2,'CONT',null,null,null),
('duas tardes e outros contos silenciosos','Duas Tardes e outros contos silenciosos','João Anzanello Carrascoza','Contos',3,'CONT',null,null,null),
('o ladrao de sonhos e outras historias','O ladrão de sonhos e outras histórias','Ivan Angelo','Contos',4,'CONT',null,null,null),
('penelope manda lembrancas','Penélope manda lembranças','Marina Colasanti','Contos',5,'CONT',null,null,null),
('contos contidos','Contos contidos','Maria Lúcia Simões','Contos',6,'CONT',null,null,null),
('contos macabros - 13 historias sinistras da literatura brasileira','Contos Macabros - 13 Histórias Sinistras da Literatura Brasileira','Lainister de Oliveira Esteves (org.)','Contos',7,'CONT',null,null,null),
('nove lendas urbanas aterrorizantes','Nove Lendas Urbanas Aterrorizantes','Ricardo Dalai e Susana Ventura','Contos',8,'CONT',null,null,null),
('venha ver o por do sol e outros contos','Venha ver o pôr do sol e outros contos','Lygia Fagundes Telles','Contos',9,'CONT',null,null,null),
('contos mais que minimos','Contos mais que mínimos','Heloisa Seixas','Contos',10,'CONT',null,null,null),
('meu rosto nao sera como o teu e outros medos','Meu rosto Não será como o Teu e outros Medos','Marcos Apostolo','Contos',11,'CONT',null,null,null),
('feliz aniversario, clarice','Feliz aniversário, Clarice','Hugo Almeida (org.)','Contos',12,'CONT',null,null,null),
('88 historias: contos e minicontos','88 Histórias: contos e minicontos','Severino Rodrigues','Contos',13,'CONT',null,null,null),
('insubmissas lagrimas de mulheres','Insubmissas Lágrimas de Mulheres','Conceição Evaristo','Contos',14,'CONT',null,null,null),
('o segredo da pedra luminosa','O Segredo da Pedra Luminosa','Jéssica Bolf','Contos',15,'CONT',null,null,null),
('quem comeu os meus biscoitos','Quem Comeu Os Meus Biscoitos','Bella Gianini','Contos',16,'CONT',null,null,null),
('medo nao identificado','MEDO Não Identificado','Júlio César Antunes da Silva','Contos',17,'CONT',null,null,null),
('25 contos de machado de assis','25 contos de Machado de Assis','Machado de Assis por Nádia Bella Gothib (org.)','Contos',18,'CONT',null,null,null),
('olhar de frente','Olhar de Frente','Martinelli, Tânia Alexandre','Literatura juvenil',null,'LJ',null,'Rosa','#ec4899'),
('o genio do crime','O Gênio do Crime','Marinho, João Carlos','Literatura juvenil',null,'LJ',null,'Rosa','#ec4899'),
('o premio/a iliada (adaptacao da obra de homero)','O Prêmio/A Ilíada (adaptação da obra de Homero)','Rodrigues, Sonia','Literatura juvenil',null,'LJ',null,'Laranja','#f59e0b'),
('a palavra magica','A palavra mágica','Scliar, Moacyr','Literatura juvenil',null,'LJ',null,'Rosa','#ec4899'),
('alice no pais da mentira','Alice No País Da Mentira','Bandeira, Pedro','Literatura juvenil',null,'LJ',null,'Rosa','#ec4899'),
('prezado ronaldo','Prezado Ronaldo','Carneiro, Flávio','Literatura juvenil',null,'LJ',null,'Rosa','#ec4899'),
('layla, a menina siria','Layla, a menina síria','Pizala, Cassiana; Awada Zahra, Rima; Vilas Boas, Rosi','Literatura juvenil',null,'LJ',null,'Rosa','#ec4899'),
('a maldicao de horrendo','A Maldição de Horrendo','Fienberg, Anna','Literatura juvenil',null,'LJ',null,'Verde','#16a34a'),
('odisseia','Odisseia','Rocha, Ruth (adaptação)','Literatura juvenil',null,'LJ',null,'Verde','#16a34a'),
('a estranha maquina extraviada','A Estranha Máquina Extraviada','Veiga. José J.','Literatura juvenil',null,'LJ',null,'Verde','#16a34a'),
('ana levada da breca','Ana Levada da Breca','Lourdes Krieger, Maria de','Literatura juvenil',null,'LJ',null,'Verde','#16a34a'),
('joao e maria e outros contos de grimm','João e Maria e outros contos de Grimm','Grimm, Jacob e Wilhelm(Org. Luiz Raul Machado)','Literatura juvenil',null,'LJ',null,'Verde','#16a34a'),
('historias bem-contadas / contos da tradicao popular brasileira','Histórias Bem-Contadas / Contos da tradição popular brasileira','Paganini, Marcia e Dalai, Ricardo','Literatura juvenil',null,'LJ',null,'Verde','#16a34a'),
('visita a baleia','Visita à baleia','Venturelli, Paulo','Literatura juvenil',null,'LJ',null,'Verde','#16a34a'),
('meu patrao nao mora mais aqui','Meu Patrão Não Mora Mais Aqui','Riter, Caio','Literatura juvenil',null,'LJ',null,'Verde','#16a34a'),
('godi - um menino chamado liberdade','Godi - um menino chamado liberdade','Ferreira, Fábio','Literatura juvenil',null,'LJ',null,'Verde','#16a34a'),
('a fabrica de nuvens','A fábrica de nuvens','Fabra, Jordi Sierra i','Literatura juvenil',null,'LJ',null,'Verde','#16a34a'),
('detetive siqueira em: o panfleto','Detetive Siqueira em: O panfleto','Jacob, Dionísio','Literatura juvenil',null,'LJ',null,'Verde','#16a34a'),
('o amor e um passaro vermelho','O amor é um pássaro vermelho','Almeida Prado, Lucília Junqueira de','Literatura juvenil',null,'LJ',null,'Verde','#16a34a'),
('um lencol de infinitos fios','Um Lençol de Infinitos Fios','Ventura, Susana','Literatura juvenil',null,'LJ',null,'Laranja','#f59e0b'),
('o anjo linguarudo','O Anjo Linguarudo','Carrasco, Walcyr','Literatura juvenil',null,'LJ',null,'Laranja','#f59e0b'),
('cara ou coroa?','Cara ou coroa?','Sabino, Fernando','Literatura juvenil',null,'LJ',null,'Laranja','#f59e0b'),
('margarida, a fada do sonho','Margarida, a Fada do Sonho','Butterfield, Moira','Literatura juvenil',null,'LJ',null,'Amarela','#eab308'),
('pra voce eu conto','Pra você eu conto','Scliar, Moacyr','Literatura juvenil',null,'LJ',null,'Rosa','#ec4899'),
('mendax - o ladrao de historias','MENDAX - O Ladrão de Histórias','Fernandes, Breno','Literatura juvenil',null,'LJ',null,'Rosa','#ec4899'),
('perdidos no tempo - dois brasileiros na roma antiga','Perdidos no Tempo - Dois Brasileiros na Roma Antiga','Regina, Silvia La','Literatura juvenil',null,'LJ',null,'Rosa','#ec4899'),
('desenho de guerra e de amor','Desenho de Guerra e de amor','Souza, Flavio','Literatura juvenil',null,'LJ',null,'Rosa','#ec4899');

update public.livros as livro
set
  ordem_planilha = coalesce(livro.ordem_planilha, origem.ordem_planilha),
  genero_codigo = coalesce(nullif(btrim(livro.genero_codigo), ''), origem.genero_codigo),
  classificacao_numero = coalesce(nullif(btrim(livro.classificacao_numero), ''), origem.classificacao_numero),
  classificacao_cor = coalesce(nullif(btrim(livro.classificacao_cor), ''), origem.classificacao_cor),
  classificacao_cor_hex = coalesce(nullif(btrim(livro.classificacao_cor_hex), ''), origem.classificacao_cor_hex)
from catalogo_planilha_original as origem
where pg_temp.normalizar_catalogo(livro.titulo) = origem.titulo_chave;

update public.exemplares as exemplar
set localizacao = origem.classificacao_numero
from public.livros as livro
join catalogo_planilha_original as origem
  on pg_temp.normalizar_catalogo(livro.titulo) = origem.titulo_chave
where exemplar.livro_id = livro.id
  and nullif(btrim(exemplar.localizacao), '') is null
  and origem.classificacao_numero is not null;

commit;

select
  (select count(*) from catalogo_planilha_original) as titulos_na_planilha,
  count(distinct livro.id) as titulos_localizados_no_banco,
  count(distinct livro.id) filter (where livro.ordem_planilha is not null) as com_ordem,
  count(distinct livro.id) filter (where livro.genero_codigo is not null) as com_codigo,
  count(distinct livro.id) filter (where livro.classificacao_numero is not null) as com_numero_ou_localizacao,
  count(distinct livro.id) filter (where livro.classificacao_cor is not null) as com_cor_original,
  coalesce(
    jsonb_agg(
      jsonb_build_object(
        'titulo', origem.titulo_original,
        'autor', origem.autor_original
      ) order by origem.titulo_original
    ) filter (where livro.id is null),
    '[]'::jsonb
  ) as titulos_nao_localizados
from catalogo_planilha_original as origem
left join public.livros as livro
  on pg_temp.normalizar_catalogo(livro.titulo) = origem.titulo_chave;
